# Generated by Django 5.2.1 on 2025-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategorie', 'verbose_name_plural': 'kategorie'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'komentarze', 'verbose_name_plural': 'komentarze'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posty'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
